const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
for(const file of ['flippy-flapper.js','flippy-flapper.esm.js']){
 const requests=[],images=[],timers=new Map();let id=0;
 class Image{constructor(){this.width=100;this.height=150;images.push(this);}set src(url){this.url=url;if(url)requests.push(url);}get src(){return this.url;}}
 const libPath=path.join(__dirname,'../lib',file),context={window:{},URL,Image,setTimeout:callback=>{timers.set(++id,callback);return id;},clearTimeout:key=>timers.delete(key),document:{createElement:()=>({width:0,height:0,getContext:()=>({fillRect(){},fillText(){},drawImage(){},translate(){},rotate(){}})})}};
 let code=fs.readFileSync(libPath,'utf8').replace(/window.FlippyFlapper=Object.freeze\([^\n]+\);/,'window.ImageCache=ImageCache;').replace(/export \{[^\n]+\};/,'window.ImageCache=ImageCache;');vm.runInNewContext(code,context,{filename:libPath});
 const manifest={pageWidth:100,pageHeight:150,pageCount:20,pages:Array.from({length:20},(_,i)=>({image:`https://test/${i+1}.webp`,sheetWidth:1,crop:0}))};
 test(`${file}: turning forward and backward reuses decoded originals and page surfaces`,async()=>{requests.length=0;const cache=new context.window.ImageCache(manifest);const first=cache.get(1);images.at(-1).onload();const result=await first;cache.preload(3,1);cache.preload(1,1);assert.equal(await cache.get(1),result);assert.equal(requests.filter(url=>url==='https://test/1.webp').length,1);cache.destroy();assert.equal(timers.size,0);});
 test(`${file}: adjacent pages preload in both directions, boundaries are respected and retention is bounded`,()=>{requests.length=0;const cache=new context.window.ImageCache(manifest,{maxCachedPages:4,maxCachedImages:3});cache.preload(5,1);assert.deepEqual(requests.slice(),['https://test/5.webp','https://test/6.webp','https://test/4.webp']);cache.preload(20,1);assert.equal(requests.includes('https://test/21.webp'),false);cache.preload(1,1);assert.equal(requests.includes('https://test/0.webp'),false);assert.ok(cache.items.size<=4);assert.ok(cache.originals.size<=3);cache.destroy();assert.equal(timers.size,0);});
 test(`${file}: two panels share one source decode and retry clears a failed original`,async()=>{requests.length=0;const same={...manifest,pages:manifest.pages.map(p=>({...p,image:'https://test/sheet.webp'}))},cache=new context.window.ImageCache(same);const one=cache.get(1),two=cache.get(2);images.at(-1).onerror();assert.equal((await one).failed,true);assert.equal((await two).failed,true);assert.equal(requests.length,1);const retry=cache.get(1,true);images.at(-1).onload();assert.equal((await retry).failed,false);assert.equal(requests.length,2);cache.destroy();});
 test(`${file}: timeout creates a recoverable failed page and destroy cancels in-flight loads`,async()=>{const cache=new context.window.ImageCache(manifest);const fail=cache.get(1);[...timers.values()].at(-1)();assert.equal((await fail).failed,true);assert.equal(images.at(-1).src,'');const inflight=cache.get(2);cache.destroy();assert.equal((await inflight).failed,true);assert.equal(cache.items.size,0);assert.equal(cache.originals.size,0);assert.equal(timers.size,0);});
}
