export interface Page { index: number; layout?: 'single'|'spread'|'foldout'|'cover'|'cover-spread'; image: string; thumbnail: string; textLayer?: string; links?: unknown[]; audio?: string | null }
export interface MagazineManifest { title: string; subtitle?: string; pageWidth: number; pageHeight: number; pageCount: number; pages: Page[] }
export interface MagazineViewerOptions { manifestUrl?: string; manifest?: MagazineManifest; baseUrl?: string; showHeader?: boolean; globalArrowKeys?: boolean; initialPage?: number; initialSourceIndex?: number; background?: string; spreadMode?: 'auto'|'always'|'never'; minSpreadPageWidth?: number; showToolbar?: boolean; showThumbnails?: boolean; enableFullscreen?: boolean; enableAutoFlip?: boolean; animatePageTurns?: boolean; autoFlipIntervalMs?: number; maxZoom?: number; pageTurnDurationMs?: number; navigationTurnDurationMs?: number; pageTurnThreshold?: number; preloadDistance?: number; showPageThickness?: boolean; showBacksideBleed?: boolean }
export interface VisiblePage { pageIndex:number; sourceIndex:number|null }
export interface ViewerState { pageCount:number; sourcePageCount:number; visiblePages:VisiblePage[]; pageIndex: number; sourceIndex:number|null; foldoutsOpen:number[]; mode:'spread'|'single'; turnState:'idle'|'loading'|'dragging'|'completing'|'canceling'; turnDirection:'forward'|'backward'|null; turnProgress:number; zoomMode:'fit'|'manual'; zoom:number; panX:number; panY:number; thumbnailsOpen:boolean; searchOpen:false; fullscreen:boolean; autoFlip:boolean }
export type ViewerEvent='pagechange'|'turnstart'|'turnend'|'zoomchange'|'fullscreenchange'|'foldoutchange';
export class MagazineViewer { constructor(element:HTMLElement,options:MagazineViewerOptions); ready:Promise<MagazineViewer>; next():Promise<void>|undefined; previous():Promise<void>|undefined; first():void; last():void; goToPage(page:number):void; zoomIn():void; zoomOut():void; fit():void; openThumbnails():void; closeThumbnails():void; enterFullscreen():Promise<void>; exitFullscreen():Promise<void>; startAutoFlip():void; stopAutoFlip():void; setSpreadMode(mode:'auto'|'always'|'never'):void; setPageTurnAnimation(enabled:boolean):void; openFoldout(page?:number):Promise<boolean>; closeFoldout(page?:number):Promise<boolean>; getState():ViewerState; on(event:ViewerEvent,callback:(event:{state:ViewerState;committed?:boolean})=>void):()=>void; destroy():void }
export function createMagazineViewer(element:HTMLElement,options:MagazineViewerOptions):MagazineViewer;

export const create: typeof createMagazineViewer;
export as namespace FlippyFlapper;
