export interface Page { index: number; width?: number; height?: number; layout?: 'auto'|'single'|'spread'|'foldout'|'cover'|'cover-spread'; region?: {x:number;y:number;width:number;height:number}; rotation?: 0|90|180|270; sourceIndex?: number; image: string; thumbnail: string; textLayer?: string; links?: unknown[]; audio?: string | null }
export interface MagazineManifest { title: string; subtitle?: string; pageWidth: number; pageHeight: number; pageCount: number; pages: Page[]; imposition?: Imposition; readingPages?: boolean; sourcePageCount?: number }
export interface MagazineViewerOptions { manifestUrl?: string; manifest?: MagazineManifest; baseUrl?: string; showHeader?: boolean; globalArrowKeys?: boolean; initialPage?: number; initialSourceIndex?: number; background?: string; spreadMode?: 'auto'|'always'|'never'; minSpreadPageWidth?: number; showToolbar?: boolean; showThumbnails?: boolean; enableFullscreen?: boolean; enableAutoFlip?: boolean; animatePageTurns?: boolean; autoFlipIntervalMs?: number; maxZoom?: number; pageTurnDurationMs?: number; navigationTurnDurationMs?: number; pageTurnThreshold?: number; preloadDistance?: number; maxCachedPages?: number; maxCachedImages?: number; showPageThickness?: boolean; showBacksideBleed?: boolean }
export interface VisiblePage { pageIndex:number; sourceIndex:number|null }
export interface ViewerState { pageCount:number; sourcePageCount:number; visiblePages:VisiblePage[]; pageIndex: number; sourceIndex:number|null; foldoutsOpen:number[]; mode:'spread'|'single'; turnState:'idle'|'loading'|'dragging'|'completing'|'canceling'; turnDirection:'forward'|'backward'|null; turnProgress:number; zoomMode:'fit'|'manual'; zoom:number; panX:number; panY:number; thumbnailsOpen:boolean; searchOpen:false; fullscreen:boolean; autoFlip:boolean }
export type ViewerEvent='pagechange'|'turnstart'|'turnend'|'zoomchange'|'fullscreenchange'|'foldoutchange';
export class MagazineViewer { constructor(element:HTMLElement,options:MagazineViewerOptions); ready:Promise<MagazineViewer>; next():Promise<void>|undefined; previous():Promise<void>|undefined; first():void; last():void; goToPage(page:number):void; zoomIn():void; zoomOut():void; fit():void; openThumbnails():void; closeThumbnails():void; enterFullscreen():Promise<void>; exitFullscreen():Promise<void>; startAutoFlip():void; stopAutoFlip():void; setSpreadMode(mode:'auto'|'always'|'never'):void; setPageTurnAnimation(enabled:boolean):void; openFoldout(page?:number):Promise<boolean>; closeFoldout(page?:number):Promise<boolean>; getState():ViewerState; on(event:ViewerEvent,callback:(event:{state:ViewerState;committed?:boolean})=>void):()=>void; destroy():void }
export function createMagazineViewer(element:HTMLElement,options:MagazineViewerOptions):MagazineViewer;

export const create: typeof createMagazineViewer;
export as namespace FlippyFlapper;

export function inferPageLayout(width:number,height:number):'single'|'spread'|'foldout';

export interface Imposition { type: 'auto'|'single'|'reader-spreads'|'booklet'|'signature'|'n-up'|'cut-stack'|'brochure'|'custom'; rows?: number; columns?: number; signaturePages?: number; fold?: 'tri-fold'|'z-fold'|'gatefold'; order?: {sourceIndex:number;cell:number;rotation?:0|90|180|270}[] }
export function applyImposition(manifest:MagazineManifest,configuration?:Imposition):MagazineManifest;
export function createImpositionEditor(element:HTMLElement,options:{sources:Page[];configuration?:Imposition;baseUrl?:string;onChange?:(configuration:Imposition,state:{valid:boolean})=>void}):{getConfiguration():Imposition;readonly valid:boolean;updateSources(sources:Page[]):void;setConfiguration(configuration:Imposition):void;destroy():void};
